//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUs
    {
        public int ID { get; set; }
        public string AboutName { get; set; }
        public string AboutContent { get; set; }
        public bool AboutHide { get; set; }
        public string AboutImage { get; set; }
    }
}
