//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.ProgramImages = new HashSet<ProgramImage>();
        }
    
        public int ID { get; set; }
        public string ProName { get; set; }
        public string ProContent { get; set; }
        public System.DateTime ProDateCreate { get; set; }
        public bool ProHide { get; set; }
        public int TypeID { get; set; }
    
        public virtual TypeProgram TypeProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramImage> ProgramImages { get; set; }
    }
}
