//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGO.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDonate
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int DonateID { get; set; }
        public string TypeCard { get; set; }
        public decimal Money { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual Donate Donate { get; set; }
        public virtual User User { get; set; }
    }
}
